ALTER TABLE users ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'PLAYER';
ALTER TABLE users ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';
UPDATE users SET role = 'ADMIN' WHERE username = 'player1';
